### PR TITLE
Solve warnings

### PR DESCRIPTION
**Pull request by DNKpp**
Hello,
I recently pulled your repository and encountered a huge wave of warnings. I changed a few parts in that code, especially those were you are using uint/size_t inconsitently.
The only remaining warning type is: `warning C4996: 'localtime': This function or variable may be unsafe. Consider using localtime_s instead.` localtime_s is a msvc function, so this should be avoided to keep the code portable.

### CODE REVIEW

**Comment by DanielChappuis** [comment]
Thanks a lot for your contribution. 

I am currently doing some refactoring in the "optimization" branch and there I am trying to use mostly uint32_t (uint32) whenever possible instead of uint. I will then try to use your changes to make sure that I don't have those warnings anymore (not sure I will able to directly merge your pull request but I will definitely use it to make sure I do not forget anything). I will probably do this for version v0.9.0 of the library.

Thanks !!

**Comment by DNKpp** [comment]
Glad that you like it.
It seems you try targeting c++11 and below, am I right?
Otherwise I would suggest to overhaul those nasty indexed for loops and potentially get rid of the custom containers and use the std versions. What is your point using these custom versions (hopefully that doesn't sound too rude :D )?

**Comment by DanielChappuis** [comment]
Yes, I am currently targeting c++11.

Many game/physics engines do not use the STL containers but custom ones.
Mostly for speed and being able to be in total control of the implementation (memory allocation, memory alignment, multi-threading). I have implemented custom list, hash map and hash set classes that are quite easy to implement. But if I need a method that is not available in the STL, it very easy for me to add it into my custom classes.

You can also read [here](https://books.google.ch/books?id=LlLSBQAAQBAJ&pg=PA261&lpg=PA261&dq=STL+also+almost+always+eats+up+more+memory+than+a+custom-designed+data+structure.&source=bl&ots=h82AA5EcHf&sig=ACfU3U1BeD24Dm0fXJBkepzIfLAT0vdHcA&hl=en&sa=X&ved=2ahUKEwj7-eyOx7nrAhXQpIsKHb8DBVgQ6AEwBHoECAoQAQ#v=onepage&q=STL%20also%20almost%20always%20eats%20up%20more%20memory%20than%20a%20custom-designed%20data%20structure.&f=false) in the book "Game Engine Architecture" by Jason Gregory some drawbacks when using the STL library in games.

**Comment by DNKpp** [comment]
Well, I get your point but I don't think I can fully agree with it. But to be honest, its totally your decision ;)
Don't get me wrong, I like your lib. If I wouldn't I would not invest time to make a pull request.

I own that book myself but, to be honest, didn't remember much of this chapter, so I quickly reread it. If I'm right, this book mostly refers to c++ prior c++11. For example the author talks about raw arrays instead of std::array (which doesn't do much more than a plain "c" array but provides a much nicer interface) which were introduced in c++11. I think I also saw a few raw arrays in your codebase, too. Each modern stl container (beside std::array of course) has the possibility to use a custom memory allocator; so it is tweakable to your needs (never did that myself).
Either way, I have two major complaints about your lib: your List implementation is more like a dynamic array (e.g. std::vector) than a list. And that confused me during my first step through your code.
The second is, that you are using the indexed loops a lot even if your container offers iterator support. "Range based for loops" where introduced in c++11 and they are a lot easier to write, maintain and read. From my personal experience with the stl I can tell, that using them is even faster than using the indexed approach , because they directly cache the end/size of the range and do not request this information during each iteration step, which is the case in most of your (and also others) hand written for loops. But that might be different with your containers.
I wouldn't complain about that, if you just provide the iterator interface to the user of your lib. But unfortunately you do not and thus the user is forced to use that indexed style, which is a pity because it prevents the use with common stl algorithms or c++20 ranges (to just name a few examples).

I hope you don't consider this text as a blame, because I really don't want to blame or tell you what you have to do with your library. I simply see the possibility to "modernize" the interface of this library a bit, so that it can be more enjoyable for the user ;)

**Comment by DanielChappuis** [comment]
> Either way, I have two major complaints about your lib: your List implementation is more like a dynamic array (e.g. std::vector) than a list. And that confused me during my first step through your code.

That's right the reactphysics3d::List class is indeed for a dynamic array (with continuous memory) like std::vector but I really don't like the "vector" name for this. I would prefer to use reactphysics3d::Array. Maybe I will rename it to Array.

> The second is, that you are using the indexed loops a lot even if your container offers iterator support. "Range based for loops" where introduced in c++11 and they are a lot easier to write, maintain and read. From my personal experience with the stl I can tell, that using them is even faster than using the indexed approach , because they directly cache the end/size of the range and do not request this information during each iteration step, which is the case in most of your (and also others) hand written for loops. But that might be different with your containers.

This is a good point. I can try to see if there is a performance benefit to use Iterators for the loops. If so, I have no problem to use iterators internally of course.

In the future, I plan to use multi-threading so that for instance on a 4 cores CPU and n bodies to update, the first core is responsible to compute the new positions for bodies 0 to n/4 in an array of positions. I think for this it is simpler to work with indices instead of iterators if I want to separate the work on an array on multiple threads.

> I wouldn't complain about that, if you just provide the iterator interface to the user of your lib. But unfortunately you do not and thus the user is forced to use that indexed style, which is a pity because it prevents the use with common stl algorithms or c++20 ranges (to just name a few examples).

Yes, I do not see any problems to do that.

> I hope you don't consider this text as a blame, because I really don't want to blame or tell you what you have to do with your library. I simply see the possibility to "modernize" the interface of this library a bit, so that it can be more enjoyable for the user ;)

No problem. It's always interesting to know what the users of the library like or dislike about it.

**Comment by DanielChappuis** [comment]
I was wondering something.

When you say:

> From my personal experience with the stl I can tell, that using them is even faster than using the indexed approach , because they directly cache the end/size of the range and do not request this information during each iteration step, which is the case in most of your (and also others) hand written for loops. But that might be different with your containers.

I am not sure I understand this actually. When using an iterator, each time we advance the iterator we need to check against the size/end of the array right ? So it's exactly the same for the index loop. Am I missing something ?

Moreover, as described and benchmarked in [this post](https://stackoverflow.com/questions/2524233/speed-accessing-a-stdvector-by-iterator-vs-by-operator-index) there should be no huge difference between the two solutions in a loop.

When you say: 

> I wouldn't complain about that, if you just provide the iterator interface to the user of your lib. But unfortunately you do not and thus the user is forced to use that indexed style, which is a pity because it prevents the use with common stl algorithms or c++20 ranges (to just name a few examples).

What do you mean exactly ? As far as I know in the ReactPhysics3D library it is possible to iterate on rp3d::List, rp3d::Set and rp3d::Map using iterators as follows:

```
rp3d::List list = ....;
for (auto item: list) {
   ...
}

for (auto it = list.begin(); it != list.end(); ++it) {
   ...
}
```


Is this not working on your side ?

**Comment by DNKpp** [comment]
Hey, sorry for the late replay. Didn't check my notifications.



> I was wondering something.
> 
> When you say:
> 
> > From my personal experience with the stl I can tell, that using them is even faster than using the indexed approach , because they directly cache the end/size of the range and do not request this information during each iteration step, which is the case in most of your (and also others) hand written for loops. But that might be different with your containers.
> 
> I am not sure I understand this actually. When using an iterator, each time we advance the iterator we need to check against the size/end of the array right ? So it's exactly the same for the index loop. Am I missing something ?
> 
> Moreover, as described and benchmarked in [this post](https://stackoverflow.com/questions/2524233/speed-accessing-a-stdvector-by-iterator-vs-by-operator-index) there should be no huge difference between the two solutions in a loop.
> 
Well, lately I performed some benchmark tests on quickbench and on my local machine. The outcome was quite interesting, because when I was using the usual setup like this:
`for (std::size_t i = 0; i < cotainer.size(); ++i){ /*...*/ }`
against
`for (auto itr = container.begin(); itr != cotainer.end(); ++itr){ /*...*/ }`
 the indexed version was a lot slower than the index version. But when I changed to cached end versions:

`for (auto size = cotainer.size(), i = 0; i < size ++i){ /*...*/ }`
against
`for (auto itr = container.begin(), end = cotainer.end(); itr != end; ++itr){ /*...*/ }`
The index version gained a huge performance push but where still slower than the iterator version. Have a look here: [https://quick-bench.com/q/-Z8vtdMWdF6uO1toADANd9FRLZ4](url)
This might come from the fact, that the stl iterators are designed to work very well with iterators and therefore a begin/end instead of a begin/size member pair is cached inside of a vector, so the size needs to be calculated each time it is requested.

I saw a lot for loops with the non-cached size in your code base. Indeed, you could simply add the caching but from my perspective its preferable to use the range-based for, because you directly access the iterated member. But that might be a matter of taste. What I try to tell is, that even when it might seem odd, caching is king. With the range-based for loop you don't have to think about that detail, because it's doing it right under the hood; and it is easier to write.

> When you say:
> 
> > I wouldn't complain about that, if you just provide the iterator interface to the user of your lib. But unfortunately you do not and thus the user is forced to use that indexed style, which is a pity because it prevents the use with common stl algorithms or c++20 ranges (to just name a few examples).
> 
> What do you mean exactly ? As far as I know in the ReactPhysics3D library it is possible to iterate on rp3d::List, rp3d::Set and rp3d::Map using iterators as follows:
> 
> ```
> rp3d::List list = ....;
> for (auto item: list) {
>    ...
> }
> 
> for (auto it = list.begin(); it != list.end(); ++it) {
>    ...
> }
> ```
> 
> Is this not working on your side ?
Yes, you are right. But you tend to hand over wrapper objects which exposes just a size and a indexed element access function. For example in your "CollisionCallback" you hand over a CallbackData object, which only exposes a `size_t getNbContactPairs() const` and `ContactPair getContactPair(size_t index) const`.

**Comment by DanielChappuis** [comment]
> Well, lately I performed some benchmark tests on quickbench and on my local machine. The outcome was quite interesting, because when I was using the usual setup like this:
> `for (std::size_t i = 0; i < cotainer.size(); ++i){ /*...*/ }`
> against
> `for (auto itr = container.begin(); itr != cotainer.end(); ++itr){ /*...*/ }`
> the indexed version was a lot slower than the iterator version. But when I changed to cached size/end versions:
> 
> `for (auto size = cotainer.size(), i = 0; i < size ++i){ /*...*/ }`
> against
> `for (auto itr = container.begin(), end = cotainer.end(); itr != end; ++itr){ /*...*/ }`
> The index version gained a huge performance push but where still slower than the iterator version. Have a look here: [click me](https://quick-bench.com/q/HhUhnkBSCeLSAgiOGMhZ46ziA-s)
> This might come from the fact, that the stl containers are designed to work very well with iterators and therefore a begin/end instead of a begin/size member pair is cached inside of a vector, so the size needs to be calculated each time it is requested.

> I saw a lot for loops with the non-cached size in your code base. Indeed, you could simply add the caching but from my perspective its preferable to use the range-based for, because you directly access the iterated member. But that might be a matter of taste. What I try to tell is, that even when it might seem odd, caching is king. With the range-based for loop you don't have to think about that detail, because it's doing it right under the hood; and it is easier to write.

Ok you mean caching the size of the container before the loop. I am currently doing some optimizations in [this branch](https://github.com/DanielChappuis/reactphysics3d/commits/optimization) where I use the "perf" profiler with flame graph to find the places to optimize. I have already find (and fixed) some places in this branch where the caching you are talking about appeared in the profiler. Thanks for the interesting benchmarks.

> Yes, you are right. But you tend to hand over wrapper objects which exposes just a size and a indexed element access function. For example in your "CollisionCallback" you hand over a CallbackData object, which only exposes a `size_t getNbContactPairs() const` and `ContactPair getContactPair(size_t index) const`.

Yes that's because my first idea what not to expose the List, Map, Set containers to the user of the library but only use them internally.

**Comment by DNKpp** [comment]
> > Yes, you are right. But you tend to hand over wrapper objects which exposes just a size and a indexed element access function. For example in your "CollisionCallback" you hand over a CallbackData object, which only exposes a `size_t getNbContactPairs() const` and `ContactPair getContactPair(size_t index) const`.
> 
> Yes that's because my first idea what not to expose the List, Map, Set containers to the user of the library but only use them internally.

How about simply exposing the iterator pair?
```
class CallbackData
{
public:
	auto rbegin() noexcept { return std::rbegin(m_Data); }
	auto rbegin() const noexcept { return std::rbegin(m_Data); }
	auto crbegin() const noexcept { return std::rbegin(m_Data); }
	auto rend() noexcept { return std::rend(m_Data); }
	auto rend() const noexcept { return std::rend(m_Data); }
	auto crend() const noexcept { return std::rend(m_Data); }
	
	auto rbegin() noexcept { return std::rbegin(m_Data); }
	auto rbegin() const noexcept { return std::rbegin(m_Data); }
	auto crbegin() const noexcept { return std::rbegin(m_Data); }
	auto rend() noexcept { return std::rend(m_Data); }
	auto rend() const noexcept { return std::rend(m_Data); }
	auto crend() const noexcept { return std::rend(m_Data); }

private:
	SomeMightyContainer m_Data;
};
```
It's kinda bloat, but on the caller side it definitely is more enjoyable (at least for me :D)

**Comment by DanielChappuis** [comment]
I am closing this pull request because most of the warnings have been fixed in the last version (v0.9.0) of the library. I have also used some fixes and comments from your pull request. Thanks a lot.

**Pull request closed without merging**
